---
- hosts: qa
  tasks:
    - name: Kernel
      debug: msg="{{ ansible_kernel }}"
    - name: Hostname
      debug: msg="{{ ansible_hostname }}"
    # - name: Distribution
    #   debug: msg="{{ ansible_distribution }}"

    ## var 用來給定輸出的名稱
    - debug: var=ansible_architecture
    - debug: var=inventory_hostname
    - debug: var=groups
    - debug: var=group_names
    # - debug: var=hostvars